### ISSUE TITLE
Tax & Price rounding issue. Incorrect TAX charged, and wrong values in admin order

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1801]
Reproduced in CubeCart 6.1.12, using the All-in-one shipping module, flat rate shipping module and a test product. Below are screen shots showing how to setup the example.  When the AIO module is set as "Tax Included" the calculation is off by 1p on the checkout page, the total should be £23.14, but it is £23.13

![image](https://user-images.githubusercontent.com/10614018/32904259-e99bc9e0-caee-11e7-965e-3ba2245718a6.png)

![image](https://user-images.githubusercontent.com/10614018/32904291-fc530fc6-caee-11e7-8ded-1bda6e3f0c22.png)

![image](https://user-images.githubusercontent.com/10614018/32904315-0b9511e6-caef-11e7-9e9c-21ca99702f17.png)

![image](https://user-images.githubusercontent.com/10614018/32904355-1ba82226-caef-11e7-922f-e74327ea5bdb.png)

![image](https://user-images.githubusercontent.com/10614018/32904446-44ff4b86-caef-11e7-9c68-a3cba19a8213.png)

However, if I set the price in AIO as £5.83, or as per my screen shot below set the price to £5.83 without tax through the flat rate module, the calcualted price is different.

![image](https://user-images.githubusercontent.com/10614018/32904581-9036996a-caef-11e7-81df-e82b70372c48.png)

![image](https://user-images.githubusercontent.com/10614018/32904592-995fb3c8-caef-11e7-87f2-a1e4c1619fd6.png)

to confuse things even  more, the price within the order Overview tab from the admin area is also wrong.. 
![image](https://user-images.githubusercontent.com/10614018/32904641-b9d81884-caef-11e7-9e79-11b669649d52.png)

And the inventory tab also shows errors..

![image](https://user-images.githubusercontent.com/10614018/32904711-e7e58e78-caef-11e7-9b0e-aba1559e2ad7.png)

**Comment by abrookbanks** [comment]
There are minimal rounding discrepancies that can crop up form time to time. Without completely rewriting the cart mathematics and juggling the logic this is one we just have to live with. I'm sorry. Thanks for the thorough report though.

**Comment by Noodleyman** [comment]
although i understand your view and respect your opinion, i do disagree. 

if a retailer cant have confidence that tax is being charged correctly or use the admin area to view accurate financial information then CubeCart cant be used with confidence by and company who charges tax. this is a fairly important, fundimental piece of functionality at the core of any ecommerce platform.

if it needs a rewrite to fix, it should get  rewrite.

**Comment by abrookbanks** [comment]
It's not happening I'm sorry.

**Comment by abrookbanks** [comment]
I've dismissed this a bit early haven't I..? I will try to reproduce it but I'm not confident for a fix. I don't think ¢1 or 1p here or there matters does it?

**Comment by abrookbanks** [comment]
I'll ask my accountant what their take on it... but yes it should be correct and I'll have a look before dismissing this again. If its overly complex then I'll leave it as it is.

**Comment by abrookbanks** [comment]
You've got a mixture of products not including tax and shipping including tax. Surely this should be consistent? Does it work when shipping prices are entered excluding tax or vice versa but the same.

**Comment by abrookbanks** [comment]
I can't reproduce this... screenshots below... 

![screen shot 2018-02-26 at 10 44 09](https://user-images.githubusercontent.com/4520803/36666297-0d1dd00a-1ae2-11e8-95b7-95d8c94ef49b.png)
![screen shot 2018-02-26 at 10 44 03](https://user-images.githubusercontent.com/4520803/36666300-0d79996c-1ae2-11e8-92ac-c6b4068e3b87.png)
![screen shot 2018-02-26 at 10 43 45](https://user-images.githubusercontent.com/4520803/36666301-0d980532-1ae2-11e8-864c-1cb11c109576.png)

**Comment by abrookbanks** [comment]
Ok I can reproduce it but only when the order has been placed???

**Comment by abrookbanks** [comment]
I don't think I can fix this because rounding happens inline or per product and/or per shipping. This means that for example you could have ..

£1.555 rounded to 2DP is £1.56 then say £5.555 rounded to £5.56 totalling £7.12. Actually £1.555 + £5.555 = £7.11.

Begs the question should it be on line items or line total? I actually don't know the answer to that. Right now CubeCart calculates it by line item.

**Comment by abrookbanks** [comment]
Now I can't reproduce it again!? WTF.. ??

**Comment by abrookbanks** [comment]
> Right now CubeCart calculates it by line item.

Actually it doesn't! Why.. due to the fact each product can have a different tax. Christ.. this blows my mind..

**Comment by abrookbanks** [comment]
Closed by mistake.

**Comment by abrookbanks** [comment]
Still not working..

**Comment by hairy-dog** [comment]
Every system I've worked on has done the calculations to at least 3dp but displayed the results at 2dp. I assumed that CC does the same. Why doesn't it?

**Comment by abrookbanks** [comment]
FFS working on wrong branch..  as if it's not confusing enough as it is..

**Comment by abrookbanks** [comment]
Commit https://github.com/cubecart/v6/commit/25e1057e1141e10b1cafd0b03c336b39d2e79b3f works well for the scenarios posted in the bug reports every combination below calculates correctly. 

**1. Item Ex VAT - Shipping Ex VAT**
**2. Item Ex VAT  - Shipping Inc VAT**
**3. Item Inc VAT - Shipping Ex VAT**
**4. Item Inc VAT - Shipping Inc VAT**

Test with VAT at 20%.

**Comment by havenswift-hosting** [comment]
Might be worth doing some tests with multiple products especially at different tax rates - outside of the UK it is more common to have multiple different tax rates for products in a basket

**Comment by abrookbanks** [comment]
CubeCart calculates tax per line item (including shipping). It has to do it this way because each item can be tax inclusive or exclusive and with a different rate. It has to have 2DP to work otherwise we have a scenario where you get 3DP amount adding up at the end incorrectly. 

5.555 + 5.555 = 11.11 (This is wrong)
5.56 + 5.56 = 11.12 (This is correct)

Imaging having even more items.. 

5.555 * 20 = 111.10
5.56 * 20 = 111.20

It's probably better for a merchant to take too much tax than too little. This solution at 2DP should be correct.

**Comment by abrookbanks** [comment]
The argument follows on whereby a merchant has the same tax for everything and say all items are inclusive or exclusive. In that scenario this may not work because they might want to calculate tax on the final numbers and not per item. 

How do we deal with that?

**Comment by abrookbanks** [comment]
500 items at 0.355 = 177.50
500 items at 0.36 = 180.00

This is a big difference and a merchant selling many low item goods is going to complain their tax figures are now wrong.

Suggestions anyone?

**Comment by abrookbanks** [comment]
So in conclusions the bug is fixed but it creates a new one for merchants selling high volumes of low value goods.

**Comment by Noodleyman** [comment]
can you give a clearer example.. is the 500 items including/excluding tax? base price? tax rate? etc :)

**Comment by havenswift-hosting** [comment]
Also do you need to look at what currency the store is using and then round to the number of dp set for that currency - not all currencies use 2dp but this is hard coded

**Comment by abrookbanks** [comment]
Sorry I appreciate you guys haven't been on my mind bending thought path on this... 

> can you give a clearer example.. is the 500 items including/excluding tax? base price? tax rate? etc :)

Imagine the calculated tax is to three decimal places and you have 500 items in the basket. Ignore the actual product prices as its not actually relevant.

> Also do you need to look at what currency the store is using and then round to the number of dp set for that currency - not all currencies use 2dp but this is hard coded

OMG .. probably. :)

I think what I am trying to get to is that with tax calculated per line item we have to use 2 decimal places to prevent this bug. However.. maybe CubeCart needs two methods to calculate taxes.

**Method 1:** Calculated by line item if we have different tax types and or mixture of tax inc/ex prices
**Method 2:** Calculated from totals ONLY if **all** products have the same tax and **all** are either inc or ex tax. 

Am I over complicating things again? I'm also hopeless at maths. Haha.

**Comment by Noodleyman** [comment]
500 items in the basket, calcualted to 3dp...  using what tax rate? what's the total price of 500 items etc? Still not enough details to work with  ;)

**Comment by abrookbanks** [comment]
Ok let me try to figure out real word examples..

**Comment by abrookbanks** [comment]
Actually I think its is indeed working ok now even with small line items. But... 

This looks wrong but it's actually correct. If the price each is set at £0.05 but includes tax it shows £0.04 but in reality it's actualy £0.041666666666667. The £0.001666666666667 for high volume orders make a significant difference. 

£0.04 * 999 = £39.96
£0.041666666666667 * 999 = £41.63

Maybe this is a separate bug. 

![screen shot 2018-02-27 at 12 10 44](https://user-images.githubusercontent.com/4520803/36728026-46690c6e-1bb7-11e8-9a05-c7b9c3404a1b.png)


![screen shot 2018-02-27 at 12 07 16](https://user-images.githubusercontent.com/4520803/36728000-2c47d2de-1bb7-11e8-9a2a-45bd329b7c8f.png)

**Comment by Noodleyman** [comment]
whilst on the subject.... the tax per item should ideally be stored in the DB on a per order basis, so perhaps as additional data in CubeCart_order_inventory. It would be useful when troubleshooting tax issues to know what CubeCart calculated each line item / item as, both including and excluding tax. This information doesn't need to be displayed in the admin area, although could be useful when doing a deep dive into tax related queries.

I think I already raised this some time ago, but can't seem to track down the request.

**Comment by abrookbanks** [comment]
> the tax per item should ideally be stored in the DB on a per order basis

Yes absolutely! I'll get that into 6.2

**Comment by Noodleyman** [comment]
@abrookbanks , just checking that as part of the validation checks you did, the admin side of things also added up correctly? In the initial example that was also out of sync

**Comment by abrookbanks** [comment]
Once the order is placed on the front end then yes as it just takes those values. The admin side has no dynamic tax calculations.

**Comment by Noodleyman** [comment]
are you 100%? In the original example the Overview tab from the admin side showed a different total to the store front and also the Inventory tab didn't add up correctly.

Just wanting to be 100% sure it's addressed :)

**Comment by abrookbanks** [comment]
ok :)

**Comment by havenswift-hosting** [comment]
> Also do you need to look at what currency the store is using and then round to the number of dp set for that currency - not all currencies use 2dp but this is hard coded

While you are looking at this again - I dont think you addressed this point ?

**Comment by abrookbanks** [comment]
Not really planning to Ian. :)

**Comment by abrookbanks** [comment]
.. unless you can make a good case for it.

**Comment by havenswift-hosting** [comment]
I doubt if there are a lot of affected sites but as it is an easy change to make (you already store the number of dp used against each currency), I cant see that it makes any sense not to ?  Why build problems into the code ?

**Comment by abrookbanks** [comment]
> as it is an easy change to make

Is it?

I'm not really concerned about reaching our market into countries that use 3DP like Bahrain, Iraq, Jordan, Kuwait, Libya & Oman. No offence to those countries.

Expecting to get hacked now. LOL

**Comment by abrookbanks** [comment]
Source https://en.wikipedia.org/wiki/ISO_4217

**Comment by Noodleyman** [comment]
what about Chili which uses 4?
Or Tunisia which uses 3

Although minor, CubeCart does support multiple currencies so it should support them fully. This should probably get it's own ticket though so as not to cross too many topics under one thread

**Comment by abrookbanks** [comment]
I think Chili mainly uses the Peso.

**Comment by havenswift-hosting** [comment]
And all the countries that dont use any like Korea and Japan - probably excluding at least a third of all countries and what would happen if somebody wants to price in some of the crypto currencies that use higher numbers of dp's

**Comment by abrookbanks** [comment]
Any less than 2 is fine it's just ones with more than which could.. oh FFS ok I'm adding this to my mountain to do... ROFL..

**Comment by abrookbanks** [comment]
Admin control panel totals matched front end.

**Comment by hairy-dog** [comment]
I'm still confused about whether this is fixed or not. 
As I understand it, you should take the per-item price, multiply that by the quantity ordered, then calculate the tax on the total of all items in the order subject to that tax rate, or (less good) on that line of the order.
You should not calculate the tax per item and multiply by the number of items in the line. That leads to discrepancies.

**Comment by abrookbanks** [comment]
It's not per item, it's per total line items. In other words item price * quantity so it works well.
