### ISSUE TITLE
Category sorting fails

### ISSUE THREAD

**Issue by chilled35** [cubecart/v6#221]
Change sort method on a category from default to say Z-A (doesn't actually matter what sort you choose), browser refreshes and decides to show you a huge red error message stating that the category doesn't exist - transpires the cat_id reference is lost in the URL.

**Comment by abrookbanks** [comment]
The fix above prevents 'selected="selected"' from being applied multiple times. I can't however reproduce the behaviour you have. Maybe you can send a sales ticket with access so we can try this first hand?
https://support.cubecart.com/index.php?/Tickets/Submit

**Comment by abrookbanks** [comment]
I've been unable to reproduce this issue since beta 5.

**Comment by chilled35** [comment]
Here's a short video I just created, demonstrating the issue: https://www.youtube.com/watch?v=z8HgBXX2__w

**Comment by abrookbanks** [comment]
Thanks, thats a massive help. The most evident thing I can see is that the URL's are all wrong and SEO paths are not working. Would it be possible to take a look at your store? If so please send the URL and FTP to our sales dept and I'll pick it up. Thanks!
https://support.cubecart.com/index.php?/Tickets/Submit

**Comment by abrookbanks** [comment]
Setup process hadn't been run so the database was still at 5.2.16

**Comment by abrookbanks** [comment]
classes/seo.class.php was modified to disable SEO URL's. This was set back to default and real cause of SEO urls not working was fixed. 
.htaccess changed from:
```RewriteRule ^(.*).html?$ /index.php?seo_path=$1 [L,QSA]```

To:
```RewriteRule ^(.*)\.html?$ /index.php?seo_path=$1 [L,QSA]```

The server can now find the index.php file. 

This change can't be made as a permanent code change sadly as it prevents the store being easily portable. Most hosting accounts are happy to work with a document relative path. The rare ones such as this need this tweak. 

More info here: https://support.cubecart.com/index.php?/Knowledgebase/Article/View/222/41/i-get-a-404-page-not-found-error-when-i-try-to-view-my-store-pages

**Comment by chilled35** [comment]
Thanks for the headsup on that relative path fix... Transpires, curing this SEO path business also fixes the category sorting issue in 'bug 220'

**Comment by abrookbanks** [comment]
You are welcome and thanks for the heads up on #220. That saves me time.

**Comment by Dirty-Butter** [comment]
I'm still having a similar issue, except I get a 403 when I try to Sort. It doesn't matter if I'm using Grid view or the other view. My URL's are SEO compliant.
